# PATTERN SNIPPETS
TWITCH_ARGS_PATTERN = r'(@[a-zA-Z;=_/0-9#\-:]+)'
CHANNEL_PATTERN = r'#([a-z0-9A-Z_]+)'
USER_PATTERN = r'([a-zA-Z0-9_-]+)!.+?'

# PATTERNS
PRIVMSG_PATTERN_TWITCH = fr'{TWITCH_ARGS_PATTERN} :{USER_PATTERN} PRIVMSG {CHANNEL_PATTERN} :(.*)'
PING_MESSAGSE_PATTERN = r'PING :(.*)'
NOTICE_MESSAGE_PATTERN = fr'{TWITCH_ARGS_PATTERN} :(.+) NOTICE {CHANNEL_PATTERN} :(.*)'
JOIN_MESSAGE_PATTERN = rf':{USER_PATTERN} JOIN {CHANNEL_PATTERN}'
PART_MESSAGE_PATTERN = rf':{USER_PATTERN} PART {CHANNEL_PATTERN}'

# Delete the pattern snippets
del TWITCH_ARGS_PATTERN, CHANNEL_PATTERN, USER_PATTERN
__all__ = ['PRIVMSG_PATTERN_TWITCH', 'PING_MESSAGSE_PATTERN', 'NOTICE_MESSAGE_PATTERN', 'JOIN_MESSAGE_PATTERN',
           'PART_MESSAGE_PATTERN']
